angular.module("calculoEnergia", []);
angular.module("calculoEnergia").controller("MainCtrl", function($scope){
    $scope.concessionarias = [
      {nome: "COELBA", valor: 0.53},
        {nome:"UHENPAL", valor:0.58},
        {nome: "CHESP", valor: 0.56},
        {nome: "CFLO", valor: 0.55},
        {nome: "HIDROPAN", valor: 0.54},
        {nome: "COCEL", valor: 0.53},
        {nome: "ELETROCAR", valor: 0.52},
        {nome: "CELPA", valor: 0.52},
        {nome: "ENF", valor: 0.52},
        {nome: "CEMIG-D", valor: 0.50},
        {nome: "AMPLA", valor: 0.50},
        {nome: "ELEKTRO", valor: 0.50},
        {nome: "EMG", valor: 0.50},
        {nome: "COPEL-DIS", valor: 0.49},
        {nome: "EEB", valor: 0.48},
        {nome: "MUXENERGIA", valor: 0.48},
        {nome: "AES-SUL", valor: 0.48},
        {nome: "FORCEL", valor: 0.47},
        {nome: "DEMEI", valor: 0.47},
        {nome: "LIGHT", valor: 0.46},
        {nome: "CEMAT", valor: 0.46},
        {nome: "EMS", valor: 0.46},
        {nome: "ESCELSA", valor: 0.46},
        {nome: "ETO", valor: 0.46},
        {nome: "SULGIPE", valor: 0.45},
        {nome: "CEEE-D", valor: 0.45},
        {nome: "IENERGIA", valor: 0.45},
        {nome: "EDEVP", valor: 0.45},
        {nome: "CAIUÁ-D", valor: 0.44},
        {nome: "RGE", valor: 0.44},
        {nome: "CELESC-DIS", valor: 0.44},
        {nome: "CPFL Santa Cruz", valor: 0.43},
        {nome: "CELG-D", valor: 0.43},
        {nome: "CERON", valor: 0.43},
        {nome: "ELETROPAULO", valor: 0.43},
        {nome: "BANDEIRANTE", valor: 0.43},
        {nome: "ELETROPAULO", valor: 0.43},
        {nome: "CEMAR", valor: 0.43},
        {nome: "ELETROACRE", valor: 0.42},
        {nome: "CNEE", valor: 0.42},
        {nome: "CPFL-Paulista", valor: 0.41},
        {nome: "CEPISA", valor: 0.41},
        {nome: "COELCE", valor: 0.41},
        {nome: "CPFL Mococa", valor: 0.41},
        {nome: "CEAL", valor: 0.41},
        {nome: "DMED", valor: 0.41},
        {nome: "ESE", valor: 0.40},
        {nome: "EBO", valor: 0.40},
        {nome: "CELPE", valor: 0.39},
        {nome: "COELBA", valor: 0.38},
        {nome: "EPB", valor: 0.37},
        {nome: "CEB-DIS", valor: 0.36},
        {nome: "COSERN", valor: 0.37},
        {nome: "CPFL- Piratininga ", valor: 0.36},
        {nome: "CPFL Leste Paulista ", valor: 0.36},
        {nome: "CERR", valor: 0.35},
        {nome: "CPFL Jaguar", valor: 0.33},
        {nome: "AmE", valor: 0.32},
        {nome: "CEA", valor: 0.30},
        {nome: "Boa Vista", valor: 0.28}
        
    ];
})